### ISSUE TITLE
Update debian release

### ISSUE THREAD

**Issue by winding-lines** [Ragnaroek/rust-on-raspberry-docker#11]
Compiling a rust program that depends on the `ring` crate fails with the following error:

`/home/cross/project/target/arm-unknown-linux-gnueabihf/release/deps/libring-2ca5101b10054897.rlib(ring-2ca5101b10054897.ring.cklkti8e-cgu.4.rcgu.o): In function `spin::once::Once$LT$T$GT$::call_once::h2af17645f2763809':
          ring.cklkti8e-cgu.4:(.text._ZN4spin4once13Once$LT$T$GT$9call_once17h2af17645f2763809E+0x74): undefined reference to `getauxval'
          ring.cklkti8e-cgu.4:(.text._ZN4spin4once13Once$LT$T$GT$9call_once17h2af17645f2763809E+0x84): undefined reference to `getauxval'
          collect2: error: ld returned 1 exit status`

I am not sure 100% what the issue is but on my Raspberry Pi (with /etc/debian_version -> 10) the `getauxval ` symbol seems to be defined in `./arm-linux-gnueabihf/libc-2.28.so`. When I run a shell in the container it looks like it's using `libc-2.13.so`.

Any thoughts?

**Comment by Ragnaroek** [comment]
Hi, I think the issue is rooted in the outdated pi-tools: https://github.com/raspberrypi/tools
We have to convince the maintainer to update it or we fork it and update it on ourself?

**Comment by winding-lines** [comment]
Great pointer, let me see if I can figure it out. We can submit a PR after/if we get it working and then see what happens.

**Comment by Ragnaroek** [comment]
If you make a PR and want to test it you simply have to update `ENV URL_GIT_PI_TOOLS=https://github.com/raspberrypi/tools.git` in der Dockerfile to your fork and build the image with 
`docker build --build-arg RUST_VERSION=1.36.0 --tag "ragnaroek/rust-raspberry:<your-local-tag-name>" .` 

I will also have a look, but that might take some time.

**Comment by winding-lines** [comment]
Michael,

There are a lot of moving pieces in pi-tools and documentation is a bit
light. A possible approach to move forward with the current `pi-tools` is
to set the SYSROOT to
`./arm-rpi-4.9.3-linux-gnueabihf/arm-linux-gnueabihf/sysroot` instead of
`arm-bcm2708hardfp-linux-gnueabi/arm-bcm2708hardfp-linux-gnueabi/sysroot`.
The `rpi-4.9.3` has libc 2.19 which has the symbol `ring` needs.

I assume `hardfp` means hardware support for floating point and I would not
want to lose that so I am not sure about this change.

See https://github.com/Ragnaroek/rust-on-raspberry-docker/pull/12

Any thoughts?
