### ISSUE TITLE
Transient platform dependencies 

### ISSUE THREAD

**Issue by mark2b** [Ragnaroek/rust-on-raspberry-docker#18]
Hi, 
My project is depended from libSDL2, and SDL2 depended from about 20 libraries and so on. Should I download full debs tree with appropriate versions ? Or there is a workaround for only top library.
I've tried with only libSDL2 but got a lot of undefined references.
I've downloaded all and got versions compatibilities hell.

**Comment by Ragnaroek** [comment]
I currently see no way around this with this cross compile docker image. Since you need the ARM libraries for linkage.

**Comment by Ragnaroek** [comment]
There is now a script to download dependencies which should make this nicer: https://github.com/Ragnaroek/rust-on-raspberry-docker#using-apt-get-to-fetch-packages
