### ISSUE TITLE
Compiling application fails

### ISSUE THREAD

**Issue by tompijls** [Ragnaroek/rust-on-raspberry-docker#2]
Hi,

I believe I managed to setup the docker container correctly. When trying to compile my app however, I get following error. Any guidance?

> Toms-iMac:Rust tompijls$ docker run --volume /Users/tompijls/Documents/Rust/kettler/:/home/cross/project --volume /Users/tompijls/Documents/Rust/cross/:/home/cross/deb-deps ragnaroek/rust-raspberry:1.14.0 build
*** Extracting target dependencies ***
Extracting: /home/cross/deb-deps/bluez_5.43-1_armhf.deb
Extracting: /home/cross/deb-deps/libbluetooth-dev_5.43-1_armhf.deb

*** Cross compiling project ***
    Updating registry `https://github.com/rust-lang/crates.io-index`
 Downloading kdri v0.4.3
 Downloading bluetooth-serial-port v0.4.1
 Downloading enum_primitive v0.1.1
 Downloading mio v0.6.2
 Downloading nix v0.7.0
 Downloading libc v0.2.20
 Downloading void v1.0.2
 Downloading cfg-if v0.1.0
 Downloading bitflags v0.4.0
 Downloading rustc_version v0.1.7
 Downloading semver v0.1.20
 Downloading num-traits v0.1.36
 Downloading slab v0.3.0
 Downloading lazycell v0.4.0
 Downloading net2 v0.2.26
 Downloading log v0.3.6
   Compiling semver v0.1.20
   Compiling rustc_version v0.1.7
   Compiling lazycell v0.4.0
   Compiling bitflags v0.4.0
   Compiling slab v0.3.0
   Compiling void v1.0.2
   Compiling cfg-if v0.1.0
   Compiling log v0.3.6
   Compiling libc v0.2.20
   Compiling net2 v0.2.26
   Compiling num-traits v0.1.36
   Compiling enum_primitive v0.1.1
   Compiling nix v0.7.0
   Compiling mio v0.6.2
   Compiling bluetooth-serial-port v0.4.1
   Compiling kdri v0.4.3
   Compiling kettler v0.1.0 (file:///home/cross/project)
error: linking with `gcc-sysroot` failed: exit code: 1
  |
  = note: "gcc-sysroot" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-L" "/home/cross/.rustup/toolchains/1.14.0-x86_64-unknown-linux-gnu/lib/rustlib/arm-unknown-linux-gnueabihf/lib" "/home/cross/project/target/arm-unknown-linux-gnueabihf/debug/kettler.0.o" "-o" "/home/cross/project/target/arm-unknown-linux-gnueabihf/debug/kettler" "-Wl,--gc-sections" "-pie" "-nodefaultlibs" "-L" "/home/cross/project/target/arm-unknown-linux-gnueabihf/debug/deps" "-L" "/home/cross/.rustup/toolchains/1.14.0-x86_64-unknown-linux-gnu/lib/rustlib/arm-unknown-linux-gnueabihf/lib" "-Wl,-Bstatic" "-Wl,-Bdynamic" "/home/cross/project/target/arm-unknown-linux-gnueabihf/debug/deps/libkdri-9723713147bf2803.rlib" "/home/cross/project/target/arm-unknown-linux-gnueabihf/debug/deps/libbluetooth_serial_port-f23155f1a81f0bc5.rlib" "/home/cross/project/target/arm-unknown-linux-gnueabihf/debug/deps/libenum_primitive-f763630b6112f8df.rlib" "/home/cross/project/target/arm-unknown-linux-gnueabihf/debug/deps/libnum_traits-92bb90166cd1857c.rlib" "/home/cross/project/target/arm-unknown-linux-gnueabihf/debug/deps/libmio-d8a3ebfe89185cdb.rlib" "/home/cross/project/target/arm-unknown-linux-gnueabihf/debug/deps/liblog-bf16bb9a4912b11d.rlib" "/home/cross/project/target/arm-unknown-linux-gnueabihf/debug/deps/libslab-69010361762af86e.rlib" "/home/cross/project/target/arm-unknown-linux-gnueabihf/debug/deps/libnet2-755d3e4f87237d0e.rlib" "/home/cross/project/target/arm-unknown-linux-gnueabihf/debug/deps/liblazycell-d53b754addaf1d91.rlib" "/home/cross/project/target/arm-unknown-linux-gnueabihf/debug/deps/libnix-56d9e0b660233faa.rlib" "/home/cross/project/target/arm-unknown-linux-gnueabihf/debug/deps/liblibc-29ef97a68464c2b7.rlib" "/home/cross/project/target/arm-unknown-linux-gnueabihf/debug/deps/libvoid-2cc31605fcb01ba1.rlib" "/home/cross/project/target/arm-unknown-linux-gnueabihf/debug/deps/libbitflags-75746cc7f0e9d928.rlib" "/home/cross/project/target/arm-unknown-linux-gnueabihf/debug/deps/libcfg_if-72c1f992b13d5087.rlib" "/home/cross/.rustup/toolchains/1.14.0-x86_64-unknown-linux-gnu/lib/rustlib/arm-unknown-linux-gnueabihf/lib/libstd-2057375968b67ddb.rlib" "/home/cross/.rustup/toolchains/1.14.0-x86_64-unknown-linux-gnu/lib/rustlib/arm-unknown-linux-gnueabihf/lib/libpanic_unwind-20b62febd4f8b14e.rlib" "/home/cross/.rustup/toolchains/1.14.0-x86_64-unknown-linux-gnu/lib/rustlib/arm-unknown-linux-gnueabihf/lib/libunwind-70c006235637ffa1.rlib" "/home/cross/.rustup/toolchains/1.14.0-x86_64-unknown-linux-gnu/lib/rustlib/arm-unknown-linux-gnueabihf/lib/librand-eee0071785e97554.rlib" "/home/cross/.rustup/toolchains/1.14.0-x86_64-unknown-linux-gnu/lib/rustlib/arm-unknown-linux-gnueabihf/lib/libcollections-29e32f0fcc1aa9f2.rlib" "/home/cross/.rustup/toolchains/1.14.0-x86_64-unknown-linux-gnu/lib/rustlib/arm-unknown-linux-gnueabihf/lib/librustc_unicode-08e94cce686650ba.rlib" "/home/cross/.rustup/toolchains/1.14.0-x86_64-unknown-linux-gnu/lib/rustlib/arm-unknown-linux-gnueabihf/lib/liballoc-2c56955b22137f5f.rlib" "/home/cross/.rustup/toolchains/1.14.0-x86_64-unknown-linux-gnu/lib/rustlib/arm-unknown-linux-gnueabihf/lib/liballoc_jemalloc-fdcec0246f2c2a65.rlib" "/home/cross/.rustup/toolchains/1.14.0-x86_64-unknown-linux-gnu/lib/rustlib/arm-unknown-linux-gnueabihf/lib/liblibc-50aa47411c753e02.rlib" "/home/cross/.rustup/toolchains/1.14.0-x86_64-unknown-linux-gnu/lib/rustlib/arm-unknown-linux-gnueabihf/lib/libcore-d096a56044617aca.rlib" "/home/cross/.rustup/toolchains/1.14.0-x86_64-unknown-linux-gnu/lib/rustlib/arm-unknown-linux-gnueabihf/lib/libcompiler_builtins-7da46c38d3cea97a.rlib" "-l" "bluetooth" "-l" "bluetooth" "-l" "util" "-l" "dl" "-l" "rt" "-l" "pthread" "-l" "gcc_s" "-l" "pthread" "-l" "c" "-l" "m" "-l" "rt" "-l" "util"
  = note: /home/cross/pi-tools/arm-bcm2708/arm-bcm2708hardfp-linux-gnueabi/arm-bcm2708hardfp-linux-gnueabi/sysroot/usr/lib/arm-linux-gnueabihf/libbluetooth.a(sdp.o): In function `sdp_read_rsp.isra.3.constprop.12':
(.text+0xf8): undefined reference to `__fdelt_chk'
collect2: error: ld returned 1 exit status

error: aborting due to previous error

error: Could not compile `kettler`.

To learn more, run the command again with --verbose.

**Comment by Ragnaroek** [comment]
From a little DuckDuck-Going I get the feeling, the libc-Version you are requesting is not compatible with the libc-version Installed in the image?
But, I do have very limited C knowledge...

**Comment by Ragnaroek** [comment]
Closing this issue, because there was no further feedback.
