### ISSUE TITLE
Problem adding libportaudio dependencies

### ISSUE THREAD

**Issue by LinusU** [Ragnaroek/rust-on-raspberry-docker#5]
I'm not sure if I'm doing something wrong on my end, but it seems like the package `libportaudio-dev_18.1-7.1_armhf` contains a `data.tar.gz` instead of **`.xz`**.

Would it be possible to have the script test for both? or should this be handled somewhere else?

link: http://ftp.debian.org/debian/pool/main/p/portaudio/libportaudio-dev_18.1-7.1_armhf.deb

**Comment by Ragnaroek** [comment]
I think I changed this from .xz to .gz some time ago. Maybe having support for both formats would be nice.
Do you have a public build script that I can use for testing. Or is it just the .deb dependency you linked that is not correctly handled?

**Comment by LinusU** [comment]
Don't have any build script pushed at the moment, but placing the linked deb file in any folder and mounting that with `--volume <path to directory>:/home/cross/deb-deps` should show the error

*edit: sorry that all my posts are so short, haven't had too much time to dig in, would probably be easy to fix if I get some time*

**Comment by Ragnaroek** [comment]
Closing this. It is an old issue and the preferred way to install dependencies is now via: https://github.com/Ragnaroek/rust-on-raspberry-docker#using-apt-get-to-fetch-packages
